### ISSUE TITLE
course statistics: numbers fucked up

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#454]
try GMB-201, numbers do not add up:

![image](https://user-images.githubusercontent.com/523235/46344486-fb8c7a80-c649-11e8-8132-e957877156f0.png)

![image](https://user-images.githubusercontent.com/523235/46344527-2545a180-c64a-11e8-9937-c806a196a5fa.png)

![image](https://user-images.githubusercontent.com/523235/46344544-32629080-c64a-11e8-94bf-192976ae8fce.png)

**Comment by Rochet2** [comment]
New reproduction instructions:

![image](https://user-images.githubusercontent.com/468816/50646361-826d2e00-0f7e-11e9-9fb2-5541e8ba237f.png)
After pressing Fetch statistics the summary and course tabs at the top will show different passed and failed results at the bottom.

Cause of the issue:
One of the lists of student numbers is filtered by the following code
```javascript
const { students } = programme
const filterStudentFn = studentNumber => students && students.includes(studentNumber)
```
Because of this some students are not in the other statistics.
